name: Dispatched Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local
        uses: actions/checkout@v4
      - name: Checkout nested
        uses: actions/checkout@v4
        with:
          repository: chamale-rac/automaton-server
          path: automaton
      - name: Create zip
        run: |
          zip -r RealSourceCode.zip automaton/src/ src/ grammars/ app.py requirements.txt
      - name: Create release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'latest'
          prerelease: true
          title: 'Development Build'
          files: |
            RealSourceCode.zip
