on:
  workflow_dispatch:

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out automaton-server
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release
        uses: "marvinpinto/action-automatic-releases@<VERSION>"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            src
